"""
Insurer Catalog
Simulated catalog of real Indian gig-worker insurance plans from 5 providers.
In production, these would be fetched from each insurer's API.
"""

INSURER_CATALOG = [

    # ─── ACKO INSURANCE ──────────────────────────────────────────────────────
    {
        "plan_id": "ACKO-GIG-001",
        "provider": "Acko General Insurance",
        "provider_logo": "⚡",
        "plan_name": "Acko Gig Shield — Shift",
        "tagline": "Per-shift protection for delivery heroes",
        "category": "accident_health",
        "target_workers": ["delivery", "driver"],
        "premium": {
            "per_shift": 15,
            "per_day": 35,
            "per_month": 399,
        },
        "coverage_amount": 200000,
        "inclusions": [
            "Road accident hospitalisation up to ₹2,00,000",
            "Accidental death benefit ₹2,00,000",
            "Ambulance charges up to ₹3,000",
            "Fractures & dislocations",
            "Permanent partial disability",
        ],
        "exclusions": [
            "Pre-existing diseases",
            "Self-inflicted injury",
            "Driving under influence of alcohol/drugs",
            "Incidents outside active shift",
        ],
        "claim_process": "File on Acko app within 48 hrs → upload photos/FIR → decision in 2 hours",
        "eligibility": "Age 18–60, smartphone required",
        "best_for": "Delivery workers doing 2-wheel delivery in urban zones",
        "highlights": ["Instant digital policy", "2-hour claim settlement", "No paperwork"],
        "provider_website": "https://www.acko.com",
        "irdai_registered": True,
        "rating": 4.4,
    },

    {
        "plan_id": "ACKO-GIG-002",
        "provider": "Acko General Insurance",
        "provider_logo": "⚡",
        "plan_name": "Acko Gig Shield — Equipment",
        "tagline": "Protect your earning tools",
        "category": "equipment",
        "target_workers": ["delivery", "freelancer"],
        "premium": {
            "per_shift": 10,
            "per_day": 22,
            "per_month": 249,
        },
        "coverage_amount": 25000,
        "inclusions": [
            "Mobile phone damage/theft up to ₹15,000",
            "Delivery bag & accessories up to ₹5,000",
            "Helmet damage up to ₹3,000",
            "Laptop/tablet for freelancers up to ₹20,000",
        ],
        "exclusions": [
            "Cosmetic damage (scratches)",
            "Loss due to forgetfulness",
            "Devices older than 3 years",
        ],
        "claim_process": "Take photos within 24 hrs → upload to Acko app → replacement or repair in 3 days",
        "eligibility": "Age 18–55, device proof required",
        "best_for": "Workers who depend on their phone/bike as primary earning tool",
        "highlights": ["Covers phone theft", "Quick replacement", "Affordable"],
        "provider_website": "https://www.acko.com",
        "irdai_registered": True,
        "rating": 4.2,
    },

    # ─── GO DIGIT INSURANCE ───────────────────────────────────────────────────
    {
        "plan_id": "DIGIT-GIG-001",
        "provider": "Go Digit General Insurance",
        "provider_logo": "🔵",
        "plan_name": "Digit Gig Care — Accident + Medical",
        "tagline": "Comprehensive accident & health cover for gig workers",
        "category": "accident_health",
        "target_workers": ["delivery", "driver", "freelancer"],
        "premium": {
            "per_shift": 20,
            "per_day": 45,
            "per_month": 499,
        },
        "coverage_amount": 300000,
        "inclusions": [
            "Accident hospitalisation up to ₹3,00,000",
            "OPD expenses up to ₹5,000/month",
            "Daily hospital cash ₹1,000/day (max 30 days)",
            "Accidental death ₹3,00,000",
            "Permanent total disability ₹3,00,000",
            "Broken bones benefit up to ₹50,000",
        ],
        "exclusions": [
            "Non-accident illness hospitalisation",
            "Cosmetic surgery",
            "Adventure sports injuries",
            "War/nuclear risks",
        ],
        "claim_process": "WhatsApp claim on +91-DIGIT → submit bills → cashless at 5,000+ hospitals",
        "eligibility": "Age 18–65, no medical tests below ₹3L coverage",
        "best_for": "Workers who want higher coverage with hospital cash benefit",
        "highlights": ["Cashless at 5000+ hospitals", "WhatsApp claims", "Daily cash benefit"],
        "provider_website": "https://www.godigit.com",
        "irdai_registered": True,
        "rating": 4.5,
    },

    {
        "plan_id": "DIGIT-GIG-002",
        "provider": "Go Digit General Insurance",
        "provider_logo": "🔵",
        "plan_name": "Digit Income Shield",
        "tagline": "Weekly income if you can't work after an accident",
        "category": "income_protection",
        "target_workers": ["delivery", "driver"],
        "premium": {
            "per_shift": 12,
            "per_day": 28,
            "per_month": 320,
        },
        "coverage_amount": 50000,
        "inclusions": [
            "Weekly income replacement ₹3,000/week (up to 13 weeks)",
            "Temporary total disability benefit",
            "Fracture benefit up to ₹20,000",
            "Mentor for claim assistance",
        ],
        "exclusions": [
            "Illness-based disability",
            "Self-inflicted injuries",
            "Pre-existing conditions",
        ],
        "claim_process": "Submit medical certificate → weekly payouts directly to bank account",
        "eligibility": "Age 20–55, must show gig platform income proof",
        "best_for": "Workers with dependents who need income continuity if injured",
        "highlights": ["Weekly salary if injured", "No lump sum confusion", "Gig-income aware"],
        "provider_website": "https://www.godigit.com",
        "irdai_registered": True,
        "rating": 4.3,
    },

    # ─── BAJAJ ALLIANZ ────────────────────────────────────────────────────────
    {
        "plan_id": "BAJAJ-GIG-001",
        "provider": "Bajaj Allianz General Insurance",
        "provider_logo": "🏛️",
        "plan_name": "Bajaj Gig Worker Protector",
        "tagline": "All-round protection backed by India's largest insurer",
        "category": "comprehensive",
        "target_workers": ["delivery", "driver", "freelancer"],
        "premium": {
            "per_shift": 25,
            "per_day": 55,
            "per_month": 599,
        },
        "coverage_amount": 500000,
        "inclusions": [
            "Accident hospitalisation up to ₹5,00,000",
            "Accidental death ₹5,00,000",
            "Third party liability up to ₹1,00,000",
            "Permanent disability ₹5,00,000",
            "Medical evacuation",
            "Critical illness lump sum ₹1,00,000 (4 illnesses)",
        ],
        "exclusions": [
            "Illness without accident cause",
            "Pre-existing conditions for first 2 years",
            "Driving without valid license",
        ],
        "claim_process": "Call 1800-209-5858 or app → surveyor visits within 24 hrs → settlement in 7 days",
        "eligibility": "Age 18–65, valid driving license for vehicle-based workers",
        "best_for": "Workers who want maximum coverage with brand trust",
        "highlights": ["Highest coverage amount", "3rd party liability included", "Trusted brand"],
        "provider_website": "https://www.bajajallianz.com",
        "irdai_registered": True,
        "rating": 4.1,
    },

    # ─── ICICI LOMBARD ────────────────────────────────────────────────────────
    {
        "plan_id": "ICICI-GIG-001",
        "provider": "ICICI Lombard General Insurance",
        "provider_logo": "🏦",
        "plan_name": "ICICI Lombard Gig Plus",
        "tagline": "Smart protection for the modern gig economy",
        "category": "accident_equipment",
        "target_workers": ["delivery", "driver", "freelancer"],
        "premium": {
            "per_shift": 18,
            "per_day": 40,
            "per_month": 449,
        },
        "coverage_amount": 250000,
        "inclusions": [
            "Personal accident up to ₹2,50,000",
            "Equipment damage (phone, laptop) up to ₹30,000",
            "Emergency medical expenses up to ₹30,000",
            "Accidental death ₹2,50,000",
            "Telemedicine consultation (unlimited)",
        ],
        "exclusions": [
            "Routine health checkups",
            "Dental treatment",
            "Maternity expenses",
            "Equipment older than 2 years",
        ],
        "claim_process": "IL Take Care App → instant claim intimation → AI-powered assessment → 3-day settlement",
        "eligibility": "Age 18–60, any gig worker",
        "best_for": "Freelancers and workers who carry expensive equipment daily",
        "highlights": ["Covers laptop/phone", "Telemedicine included", "AI claim assessment"],
        "provider_website": "https://www.icicilombard.com",
        "irdai_registered": True,
        "rating": 4.3,
    },

    # ─── NAVI INSURANCE ───────────────────────────────────────────────────────
    {
        "plan_id": "NAVI-GIG-001",
        "provider": "Navi General Insurance",
        "provider_logo": "🟢",
        "plan_name": "Navi Micro Health Shield",
        "tagline": "Affordable health cover starting at ₹12/day",
        "category": "health",
        "target_workers": ["delivery", "driver", "freelancer"],
        "premium": {
            "per_shift": 8,
            "per_day": 12,
            "per_month": 199,
        },
        "coverage_amount": 100000,
        "inclusions": [
            "Any hospitalisation up to ₹1,00,000",
            "Day-care procedures (200+ covered)",
            "Pre- and post-hospitalisation (30/60 days)",
            "COVID-19 treatment",
            "Mental health treatment included",
        ],
        "exclusions": [
            "Cosmetic surgery",
            "Non-allopathic treatment",
            "First 30 days waiting period (new enrolment)",
        ],
        "claim_process": "Navi app → scan hospital bill → instant reimbursement within 30 minutes",
        "eligibility": "Age 18–45, no pre-existing for first 2 years",
        "best_for": "Low-income workers who just need basic hospitalisation cover at lowest cost",
        "highlights": ["Cheapest option", "30-min reimbursement", "Covers COVID & mental health"],
        "provider_website": "https://navi.com",
        "irdai_registered": True,
        "rating": 4.0,
    },

    {
        "plan_id": "NAVI-GIG-002",
        "provider": "Navi General Insurance",
        "provider_logo": "🟢",
        "plan_name": "Navi Accident Plus",
        "tagline": "Pure accident cover — cheapest on the market",
        "category": "accident",
        "target_workers": ["delivery", "driver"],
        "premium": {
            "per_shift": 5,
            "per_day": 10,
            "per_month": 149,
        },
        "coverage_amount": 100000,
        "inclusions": [
            "Accidental death ₹1,00,000",
            "Permanent total disability ₹1,00,000",
            "Permanent partial disability (proportional)",
            "Fracture benefit up to ₹15,000",
        ],
        "exclusions": [
            "Medical illness",
            "Suicide or self-harm",
            "Under the influence of substances",
        ],
        "claim_process": "SMS 'CLAIM' to 56161 → agent calls back → settlement in 5 days",
        "eligibility": "Age 18–60, no documentation required at enrolment",
        "best_for": "Workers on the tightest budget who want at least death/disability cover",
        "highlights": ["Lowest premium (₹5/shift)", "No documentation", "Simple SMS claim"],
        "provider_website": "https://navi.com",
        "irdai_registered": True,
        "rating": 3.9,
    },
]
